# Generated by Django 2.0.9 on 2020-03-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiler', '0003_profile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
    ]
