# Generated by Django 2.0.9 on 2020-03-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(blank=True, max_length=32)),
                ('_surname', models.CharField(blank=True, max_length=32)),
                ('_phone_number', models.CharField(blank=True, max_length=10)),
                ('_mail', models.CharField(blank=True, max_length=32)),
                ('_address', models.CharField(blank=True, max_length=48)),
            ],
        ),
    ]
